title: 방효성 | Portfolio
description: "Network / DevOps Engineer"
url: "https://ganplankk.github.io"
baseurl: ""

theme: jekyll-theme-chirpy

lang: ko-KR

plugins:
  - jekyll-paginate
  - jekyll-archives
  - jemoji
  - jekyll-redirect-from
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-sitemap

paginate: 10
paginate_path: "/page:num/"

jekyll-archives:
  enabled: [categories, tags]
  layout: archive
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
